### ISSUE TITLE
add movie throws server error (sqlalchemy.exc.ProgrammingError)

### ISSUE THREAD

**Issue by janfilips** [dgonzo27/fastapi-demo#1]
fastapi-demo-api-1  | 2022-03-31 12:54.42 [debug    ] add_movie
fastapi-demo-api-1  | 2022-03-31 12:54:42,835 INFO sqlalchemy.engine.Engine BEGIN (implicit)
fastapi-demo-api-1  | 2022-03-31 12:54:42,838 INFO sqlalchemy.engine.Engine INSERT INTO movie (title, year, description) VALUES (%s, %s, %s) RETURNING movie.id
fastapi-demo-api-1  | 2022-03-31 12:54:42,838 INFO sqlalchemy.engine.Engine [cached since 93.81s ago] ('test', 1, 'abcd')
fastapi-demo-db-1   | 2022-03-31 12:54:42.841 UTC [69] ERROR:  relation "movie" does not exist at character 13
fastapi-demo-db-1   | 2022-03-31 12:54:42.841 UTC [69] STATEMENT:  INSERT INTO movie (title, year, description) VALUES ($1::varchar, $2::integer, $3::varchar) RETURNING movie.id
fastapi-demo-api-1  | 2022-03-31 12:54:42,843 INFO sqlalchemy.engine.Engine ROLLBACK
fastapi-demo-api-1  | INFO:     172.18.0.1:62368 - "POST /movies HTTP/1.1" 500 Internal Server Error
fastapi-demo-api-1  | ERROR:    Exception in ASGI application
fastapi-demo-api-1  | Traceback (most recent call last):
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 418, in _prepare_and_execute
fastapi-demo-api-1  |     prepared_stmt, attributes = await adapt_connection._prepare(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 660, in _prepare
fastapi-demo-api-1  |     prepared_stmt = await self._connection.prepare(operation)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 566, in prepare
fastapi-demo-api-1  |     return await self._prepare(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 584, in _prepare
fastapi-demo-api-1  |     stmt = await self._get_statement(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 398, in _get_statement
fastapi-demo-api-1  |     statement = await self._protocol.prepare(
fastapi-demo-api-1  |   File "asyncpg/protocol/protocol.pyx", line 168, in prepare
fastapi-demo-api-1  | asyncpg.exceptions.UndefinedTableError: relation "movie" does not exist
fastapi-demo-api-1  | 
fastapi-demo-api-1  | The above exception was the direct cause of the following exception:
fastapi-demo-api-1  | 
fastapi-demo-api-1  | Traceback (most recent call last):
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
fastapi-demo-api-1  |     self.dialect.do_execute(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
fastapi-demo-api-1  |     cursor.execute(statement, parameters)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
fastapi-demo-api-1  |     self._adapt_connection.await_(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
fastapi-demo-api-1  |     return current.driver.switch(awaitable)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
fastapi-demo-api-1  |     value = await result
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
fastapi-demo-api-1  |     self._handle_exception(error)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
fastapi-demo-api-1  |     self._adapt_connection._handle_exception(error)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
fastapi-demo-api-1  |     raise translated_error from error
fastapi-demo-api-1  | sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedTableError'>: relation "movie" does not exist
fastapi-demo-api-1  | 
fastapi-demo-api-1  | The above exception was the direct cause of the following exception:
fastapi-demo-api-1  | 
fastapi-demo-api-1  | Traceback (most recent call last):
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
fastapi-demo-api-1  |     result = await app(self.scope, self.receive, self.send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
fastapi-demo-api-1  |     return await self.app(scope, receive, send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
fastapi-demo-api-1  |     await super().__call__(scope, receive, send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
fastapi-demo-api-1  |     await self.middleware_stack(scope, receive, send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
fastapi-demo-api-1  |     raise exc
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
fastapi-demo-api-1  |     await self.app(scope, receive, _send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
fastapi-demo-api-1  |     raise exc
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
fastapi-demo-api-1  |     await self.app(scope, receive, sender)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
fastapi-demo-api-1  |     await route.handle(scope, receive, send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
fastapi-demo-api-1  |     await self.app(scope, receive, send)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
fastapi-demo-api-1  |     response = await func(request)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
fastapi-demo-api-1  |     raw_response = await run_endpoint_function(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
fastapi-demo-api-1  |     return await dependant.call(**values)
fastapi-demo-api-1  |   File "/usr/src/./app/main.py", line 53, in add_movie
fastapi-demo-api-1  |     await session.commit()
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 578, in commit
fastapi-demo-api-1  |     return await greenlet_spawn(self.sync_session.commit)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
fastapi-demo-api-1  |     result = context.switch(value)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
fastapi-demo-api-1  |     self._transaction.commit(_to_root=self.future)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
fastapi-demo-api-1  |     self._prepare_impl()
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
fastapi-demo-api-1  |     self.session.flush()
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
fastapi-demo-api-1  |     self._flush(objects)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
fastapi-demo-api-1  |     transaction.rollback(_capture_exception=True)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fastapi-demo-api-1  |     compat.raise_(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
fastapi-demo-api-1  |     raise exception
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
fastapi-demo-api-1  |     flush_context.execute()
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
fastapi-demo-api-1  |     rec.execute(self)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
fastapi-demo-api-1  |     util.preloaded.orm_persistence.save_obj(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
fastapi-demo-api-1  |     _emit_insert_statements(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1237, in _emit_insert_statements
fastapi-demo-api-1  |     result = connection._execute_20(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1620, in _execute_20
fastapi-demo-api-1  |     return meth(self, args_10style, kwargs_10style, execution_options)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
fastapi-demo-api-1  |     return connection._execute_clauseelement(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1487, in _execute_clauseelement
fastapi-demo-api-1  |     ret = self._execute_context(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context
fastapi-demo-api-1  |     self._handle_dbapi_exception(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2032, in _handle_dbapi_exception
fastapi-demo-api-1  |     util.raise_(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
fastapi-demo-api-1  |     raise exception
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
fastapi-demo-api-1  |     self.dialect.do_execute(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
fastapi-demo-api-1  |     cursor.execute(statement, parameters)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
fastapi-demo-api-1  |     self._adapt_connection.await_(
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
fastapi-demo-api-1  |     return current.driver.switch(awaitable)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
fastapi-demo-api-1  |     value = await result
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
fastapi-demo-api-1  |     self._handle_exception(error)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
fastapi-demo-api-1  |     self._adapt_connection._handle_exception(error)
fastapi-demo-api-1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
fastapi-demo-api-1  |     raise translated_error from error
fastapi-demo-api-1  | sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "movie" does not exist
fastapi-demo-api-1  | [SQL: INSERT INTO movie (title, year, description) VALUES (%s, %s, %s) RETURNING movie.id]
fastapi-demo-api-1  | [parameters: ('test', 1, 'abcd')]
fastapi-demo-api-1  | (Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by dgonzo27** [comment]
the database tables don't exist in your local database
